"use client";

import { useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { jsPDF } from "jspdf";

interface GenerationResult {
  type: string;
  content: string;
}

const TAB_LABELS: Record<string, string> = {
  instagram: "Instagram Carousel",
  facebook: "Facebook Post",
  email: "Email Campaign",
  openhouse: "Open House",
  sms: "SMS Sequence",
  video: "Video Script",
};

const TAB_ICONS: Record<string, string> = {
  instagram: "📸",
  facebook: "📘",
  email: "📧",
  openhouse: "🏠",
  sms: "💬",
  video: "🎬",
};

export default function GeneratePage() {
  const { status } = useSession();
  const router = useRouter();
  const { toast } = useToast();

  const [form, setForm] = useState({
    address: "",
    price: "",
    beds: "",
    baths: "",
    sqft: "",
    description: "",
    features: "",
    agentName: "",
    brokerage: "",
  });

  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<GenerationResult[]>([]);

  if (status === "unauthenticated") {
    router.push("/login");
    return null;
  }

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setResults([]);

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      const data = await res.json();
      if (!res.ok) {
        toast({
          title: "Error",
          description: data.error || "Generation failed",
          variant: "destructive",
        });
        setLoading(false);
        return;
      }

      setResults(data.generations);
      toast({
        title: "Content Generated!",
        description: "Your marketing content pack is ready.",
      });
    } catch {
      toast({
        title: "Error",
        description: "Something went wrong. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied!", description: "Content copied to clipboard." });
  };

  const downloadPDF = (type: string, content: string) => {
    const doc = new jsPDF();
    const title = TAB_LABELS[type] || type;

    doc.setFontSize(18);
    doc.setTextColor(30, 58, 95);
    doc.text(title, 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${form.address} | ${form.price}`, 20, 35);

    doc.setDrawColor(212, 175, 55);
    doc.setLineWidth(0.5);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(content, 170);
    doc.text(lines, 20, 50);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by ListingLaunch", 20, 285);

    doc.save(`${form.address.replace(/\s+/g, "-")}-${type}.pdf`);
  };

  if (status === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-500">Loading...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl font-bold text-[#1E3A5F] mb-2">
          Generate Content Pack
        </h1>
        <p className="text-gray-600 mb-8">
          Enter your listing details to generate a full marketing content kit.
        </p>

        {/* Input Form */}
        {results.length === 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Listing Details</CardTitle>
              <CardDescription>
                Fill in the property information below.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleGenerate} className="space-y-6">
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="address">Property Address</Label>
                    <Input
                      id="address"
                      name="address"
                      value={form.address}
                      onChange={handleChange}
                      placeholder="123 Main St, Beverly Hills, CA 90210"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="price">Listing Price</Label>
                    <Input
                      id="price"
                      name="price"
                      value={form.price}
                      onChange={handleChange}
                      placeholder="$1,250,000"
                      required
                    />
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="beds">Beds</Label>
                    <Input
                      id="beds"
                      name="beds"
                      type="number"
                      value={form.beds}
                      onChange={handleChange}
                      placeholder="4"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="baths">Baths</Label>
                    <Input
                      id="baths"
                      name="baths"
                      type="number"
                      step="0.5"
                      value={form.baths}
                      onChange={handleChange}
                      placeholder="3"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="sqft">Sq Ft</Label>
                    <Input
                      id="sqft"
                      name="sqft"
                      type="number"
                      value={form.sqft}
                      onChange={handleChange}
                      placeholder="2800"
                      required
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="description">Listing Description</Label>
                  <Textarea
                    id="description"
                    name="description"
                    value={form.description}
                    onChange={handleChange}
                    placeholder="Describe the property, neighborhood, and what makes it special..."
                    rows={4}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="features">Key Features</Label>
                  <Textarea
                    id="features"
                    name="features"
                    value={form.features}
                    onChange={handleChange}
                    placeholder="Pool, updated kitchen, hardwood floors, mountain views..."
                    rows={2}
                    required
                  />
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="agentName">Agent Name</Label>
                    <Input
                      id="agentName"
                      name="agentName"
                      value={form.agentName}
                      onChange={handleChange}
                      placeholder="Jane Smith"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="brokerage">Brokerage</Label>
                    <Input
                      id="brokerage"
                      name="brokerage"
                      value={form.brokerage}
                      onChange={handleChange}
                      placeholder="Luxury Realty Group"
                    />
                  </div>
                </div>

                <Button
                  type="submit"
                  className="w-full bg-[#D4AF37] text-[#1E3A5F] hover:bg-[#c9a432] font-bold text-lg py-6"
                  disabled={loading}
                >
                  {loading
                    ? "Generating 6 content pieces..."
                    : "Generate Content Pack"}
                </Button>
              </form>
            </CardContent>
          </Card>
        )}

        {/* Loading state */}
        {loading && (
          <Card className="mt-8">
            <CardContent className="py-16 text-center">
              <div className="animate-spin w-12 h-12 border-4 border-[#D4AF37] border-t-transparent rounded-full mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-[#1E3A5F]">
                Generating your content pack...
              </h3>
              <p className="text-gray-500 mt-2">
                AI is creating 6 pieces of marketing content. This may take
                30-60 seconds.
              </p>
            </CardContent>
          </Card>
        )}

        {/* Results */}
        {results.length > 0 && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold text-[#1E3A5F]">
                  Content Pack Ready
                </h2>
                <p className="text-gray-600">
                  {form.address} — {form.price}
                </p>
              </div>
              <Button
                variant="outline"
                onClick={() => {
                  setResults([]);
                  setForm({
                    address: "",
                    price: "",
                    beds: "",
                    baths: "",
                    sqft: "",
                    description: "",
                    features: "",
                    agentName: "",
                    brokerage: "",
                  });
                }}
              >
                New Listing
              </Button>
            </div>

            <Tabs defaultValue={results[0]?.type} className="w-full">
              <TabsList className="w-full flex flex-wrap h-auto gap-1 bg-gray-100 p-1">
                {results.map((r) => (
                  <TabsTrigger
                    key={r.type}
                    value={r.type}
                    className="flex-1 min-w-[140px] text-xs sm:text-sm data-[state=active]:bg-[#1E3A5F] data-[state=active]:text-white"
                  >
                    <span className="mr-1">{TAB_ICONS[r.type]}</span>
                    <span className="hidden sm:inline">
                      {TAB_LABELS[r.type]}
                    </span>
                    <span className="sm:hidden">
                      {TAB_LABELS[r.type]?.split(" ")[0]}
                    </span>
                  </TabsTrigger>
                ))}
              </TabsList>

              {results.map((r) => (
                <TabsContent key={r.type} value={r.type}>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between">
                      <div>
                        <CardTitle className="text-[#1E3A5F]">
                          {TAB_ICONS[r.type]} {TAB_LABELS[r.type]}
                        </CardTitle>
                      </div>
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => copyToClipboard(r.content)}
                        >
                          Copy
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => downloadPDF(r.type, r.content)}
                          className="border-[#D4AF37] text-[#D4AF37] hover:bg-[#D4AF37] hover:text-[#1E3A5F]"
                        >
                          PDF
                        </Button>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <pre className="whitespace-pre-wrap text-sm leading-relaxed text-gray-700 font-[family-name:var(--font-geist-sans)]">
                        {r.content}
                      </pre>
                    </CardContent>
                  </Card>
                </TabsContent>
              ))}
            </Tabs>
          </div>
        )}
      </div>
    </div>
  );
}
